connector:
  tuya:
    region: EU

  solarman:
    region: IN
#    appid:
#    secret:
#    username:
#    password:
#    password-hash:
#    logger-sn:
smart:
  tuya:
    temp-set-min: 5
    temp-set-max: 24
    category-for-control-powers: wk
  solarman:
    timeout-sec: "${SOLARMAN_TIMEOUT_SEC:300}"
    bat-soc-min-min: "${SOLARMAN_BAT_SOC_MIN_MIN:50.0}"
    bat-soc-min-max: "${SOLARMAN_BAT_SOC_MIN_MAX:80.0}"
    bat-soc-max: "${SOLARMAN_BAT_SOC_MAX:97.0}"
    bat-soc-alarm-warn: "${SOLARMAN_BAT_SOC_ALARM_WARN:70.0}"
    bat-soc-alarm-error: "${SOLARMAN_BAT_SOC_ALARM_ERROR:40.0}"
    station-consumption-power:  "${SOLARMAN_STATION_CONSUMPTION_POWER:75.0}"

logging.level:
  ch.qos.logback: OFF
  org.apache.pulsar: OFF

---
spring.config.activate.on-cloud-platform: kubernetes

