connector:
  tuya:
    ak: "${TUYA_AK:}"
    sk: "${TUYA_SK:}"
    region: "${TUYA_REGION:EU}"
    device_ids: "${TUYA_DEVICE_IDS:}"
    user_uid: "${TUYA_USER_UID:}"
  solarman:
    region: IN
    appid: 202301101205420
    secret: fc1b5e7126f37fd1410f74021f8f3239
    username: nick@avalr.com.ua
    password: i30ASX2107
#    password-hash:
    logger-sn: 2725562730
smart:
  tuya:
    temp_set:
      min: "${TUYA_TEMP_SET_MIN:5}"
      max: "${TUYA_TEMP_SET_MAX:24}"
    category_for_control_powers: "${TUYA_CATEGORY_FOR_CONTROL_POWERS:wk}"
  solarman:
    timeout-sec: "${SOLARMAN_TIMEOUT_SEC:600}"
    bms-soc-min: "${SOLARMAN_BMS_SOC_MIN:87.0}"
    bms-soc-max: "${SOLARMAN_BMS_SOC_MAX:95.0}"
    bms-soc-alarm-warn: "${SOLARMAN_BMS_SOC_ALARM_WARN:80.0}"
    bms-soc-alarm-error: "${SOLARMAN_BMS_SOC_ALARM_ERROR:59.0}"

logging.level:
  ch.qos.logback: OFF
  org.apache.pulsar: OFF

---
spring.config.activate.on-cloud-platform: kubernetes

