connector:
  tuya:
    region: EU

  solarman:
    region: IN
#    appid:
#    secret:
#    username:
#    password:
#    password-hash:
#    logger-sn:
smart:
  tuya:
    temp-set-min: 5
    temo-set-max: 24
    category-for-control-powers: wk
  solarman:
    timeout-sec: "${SOLARMAN_TIMEOUT_SEC:600}"
    bms-soc-min: "${SOLARMAN_BMS_SOC_MIN:87.0}"
    bms-soc-max: "${SOLARMAN_BMS_SOC_MAX:95.0}"
    bms-soc-alarm-warn: "${SOLARMAN_BMS_SOC_ALARM_WARN:80.0}"
    bms-soc-alarm-error: "${SOLARMAN_BMS_SOC_ALARM_ERROR:59.0}"

logging.level:
  ch.qos.logback: OFF
  org.apache.pulsar: OFF

---
spring.config.activate.on-cloud-platform: kubernetes

